import { Client, Pet, Appointment, InventoryItem, VaccineReminder, RevenueData } from '../types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Sarah Connor',
    email: 'sarah.c@sky.net',
    phone: '(555) 019-2834',
    petsCount: 2,
    joinedDate: '2025-01-12',
  },
  {
    id: 'c2',
    name: 'Bruce Wayne',
    email: 'bruce@waynecorp.com',
    phone: '(555) 902-1245',
    petsCount: 1,
    joinedDate: '2025-02-28',
  },
  {
    id: 'c3',
    name: 'Elena Gilbert',
    email: 'elena@mysticfalls.org',
    phone: '(555) 234-5678',
    petsCount: 3,
    joinedDate: '2024-11-05',
  },
  {
    id: 'c4',
    name: 'Peter Parker',
    email: 'peter.parker@dailybugle.com',
    phone: '(555) 876-5432',
    petsCount: 1,
    joinedDate: '2025-03-15',
  },
  {
    id: 'c5',
    name: 'Arya Stark',
    email: 'no-one@winterfell.gov',
    phone: '(555) 345-6789',
    petsCount: 1,
    joinedDate: '2024-08-22',
  },
];

export const mockPets: Pet[] = [
  {
    id: 'p1',
    name: 'Max',
    species: 'dog',
    breed: 'German Shepherd',
    age: '3 years',
    ownerName: 'Sarah Connor',
    ownerId: 'c1',
    lastVisit: '2026-05-10',
  },
  {
    id: 'p2',
    name: 'Luna',
    species: 'cat',
    breed: 'Siamese',
    age: '2 years',
    ownerName: 'Sarah Connor',
    ownerId: 'c1',
    lastVisit: '2026-05-24',
  },
  {
    id: 'p3',
    name: 'Ace',
    species: 'dog',
    breed: 'Great Dane',
    age: '5 years',
    ownerName: 'Bruce Wayne',
    ownerId: 'c2',
    lastVisit: '2026-05-18',
  },
  {
    id: 'p4',
    name: 'Gilbert',
    species: 'rabbit',
    breed: 'Angora',
    age: '1 year',
    ownerName: 'Elena Gilbert',
    ownerId: 'c3',
    lastVisit: '2026-04-30',
  },
  {
    id: 'p5',
    name: 'Milo',
    species: 'cat',
    breed: 'Tabby',
    age: '4 years',
    ownerName: 'Elena Gilbert',
    ownerId: 'c3',
    lastVisit: '2026-05-25',
  },
  {
    id: 'p6',
    name: 'Bella',
    species: 'dog',
    breed: 'Golden Retriever',
    age: '6 months',
    ownerName: 'Elena Gilbert',
    ownerId: 'c3',
    lastVisit: '2026-05-20',
  },
  {
    id: 'p7',
    name: 'Webby',
    species: 'other',
    breed: 'Jumping Spider',
    age: '10 months',
    ownerName: 'Peter Parker',
    ownerId: 'c4',
    lastVisit: '2026-05-01',
  },
  {
    id: 'p8',
    name: 'Nymeria',
    species: 'dog',
    breed: 'Siberian Husky',
    age: '4 years',
    ownerName: 'Arya Stark',
    ownerId: 'c5',
    lastVisit: '2026-05-15',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    petName: 'Max',
    petSpecies: 'dog',
    ownerName: 'Sarah Connor',
    date: '2026-05-26',
    time: '09:00 AM',
    type: 'Consultation',
    status: 'Checked-in',
    veterinarian: 'Dr. Elizabeth Blackwell',
    notes: 'Annual physical and rabies booster check-up.',
  },
  {
    id: 'a2',
    petName: 'Milo',
    petSpecies: 'cat',
    ownerName: 'Elena Gilbert',
    date: '2026-05-26',
    time: '10:30 AM',
    type: 'Surgery',
    status: 'In-Progress',
    veterinarian: 'Dr. James Herriot',
    notes: 'Routine neuter surgery. Monitor post-op recovery closely.',
  },
  {
    id: 'a3',
    petName: 'Ace',
    petSpecies: 'dog',
    ownerName: 'Bruce Wayne',
    date: '2026-05-26',
    time: '01:15 PM',
    type: 'Check-up',
    status: 'Scheduled',
    veterinarian: 'Dr. Elizabeth Blackwell',
    notes: 'Check progress on ear infection. Follow-up drop application.',
  },
  {
    id: 'a4',
    petName: 'Gilbert',
    petSpecies: 'rabbit',
    ownerName: 'Elena Gilbert',
    date: '2026-05-26',
    time: '03:00 PM',
    type: 'Vaccination',
    status: 'Scheduled',
    veterinarian: 'Dr. James Herriot',
    notes: 'RHDV2 annual booster vaccination.',
  },
  {
    id: 'a5',
    petName: 'Nymeria',
    petSpecies: 'dog',
    ownerName: 'Arya Stark',
    date: '2026-05-27',
    time: '11:00 AM',
    type: 'Dental',
    status: 'Scheduled',
    veterinarian: 'Dr. Elizabeth Blackwell',
    notes: 'Ultrasonic scaling and polish.',
  },
  {
    id: 'a6',
    petName: 'Webby',
    petSpecies: 'other',
    ownerName: 'Peter Parker',
    date: '2026-05-27',
    time: '02:30 PM',
    type: 'Check-up',
    status: 'Scheduled',
    veterinarian: 'Dr. James Herriot',
    notes: 'Molting consultation and vivarium setup review.',
  },
  {
    id: 'a7',
    petName: 'Luna',
    petSpecies: 'cat',
    ownerName: 'Sarah Connor',
    date: '2026-05-25',
    time: '04:00 PM',
    type: 'Consultation',
    status: 'Completed',
    veterinarian: 'Dr. James Herriot',
    notes: 'Appetite loss. Diagnosed mild gastritis, prescribed anti-emetics.',
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 'i1',
    name: 'Amoxicillin 250mg Tablets',
    sku: 'MED-AMX-250',
    category: 'Medication',
    stock: 120,
    minStock: 200,
    unit: 'Tablets',
    price: 0.85,
  },
  {
    id: 'i2',
    name: 'Rabies Vaccine (Defensor 3)',
    sku: 'VAC-RAB-DEF',
    category: 'Medication',
    stock: 14,
    minStock: 50,
    unit: 'Vials',
    price: 15.00,
  },
  {
    id: 'i3',
    name: 'Royal Canin Gastrointestinal Dog Food',
    sku: 'FOD-RCG-DOG',
    category: 'Food',
    stock: 8,
    minStock: 10,
    unit: 'Bags (15lb)',
    price: 78.50,
  },
  {
    id: 'i4',
    name: 'Disposable Syringes 3ml',
    sku: 'SUP-SYR-3ML',
    category: 'Supplies',
    stock: 850,
    minStock: 300,
    unit: 'Pieces',
    price: 0.12,
  },
  {
    id: 'i5',
    name: 'Surgical Gloves (Size 7.5)',
    sku: 'SUP-GLV-75',
    category: 'Supplies',
    stock: 45,
    minStock: 100,
    unit: 'Pairs',
    price: 2.50,
  },
];

export const mockVaccineReminders: VaccineReminder[] = [
  {
    id: 'v1',
    petName: 'Max',
    petSpecies: 'dog',
    vaccineName: 'DHPP (Distemper/Parvo)',
    dueDate: '2026-06-02',
    ownerName: 'Sarah Connor',
    ownerEmail: 'sarah.c@sky.net',
    status: 'Pending',
  },
  {
    id: 'v2',
    petName: 'Luna',
    petSpecies: 'cat',
    vaccineName: 'FVRCP (Feline Viral Rhinotracheitis)',
    dueDate: '2026-06-15',
    ownerName: 'Sarah Connor',
    ownerEmail: 'sarah.c@sky.net',
    status: 'Pending',
  },
  {
    id: 'v3',
    petName: 'Ace',
    petSpecies: 'dog',
    vaccineName: 'Bordetella (Kennel Cough)',
    dueDate: '2026-05-20',
    ownerName: 'Bruce Wayne',
    ownerEmail: 'bruce@waynecorp.com',
    status: 'Overdue',
  },
  {
    id: 'v4',
    petName: 'Milo',
    petSpecies: 'cat',
    vaccineName: 'Rabies Booster',
    dueDate: '2026-06-28',
    ownerName: 'Elena Gilbert',
    ownerEmail: 'elena@mysticfalls.org',
    status: 'Pending',
  },
];

export const mockRevenueData: RevenueData[] = [
  { date: 'May 20', amount: 2450, appointments: 12 },
  { date: 'May 21', amount: 3100, appointments: 15 },
  { date: 'May 22', amount: 1850, appointments: 9 },
  { date: 'May 23', amount: 2900, appointments: 14 },
  { date: 'May 24', amount: 4200, appointments: 18 },
  { date: 'May 25', amount: 3500, appointments: 16 },
  { date: 'May 26', amount: 3880, appointments: 17 }, // Today
];
